// Mock product data – 30+ items for a full-fletched experience
export const products = [
  // ── Electronics ──
  {
    id: 1,
    title: "Sony WH-1000XM5 Noise Cancelling Headphones",
    category: "Electronics",
    price: 348,
    originalPrice: 399,
    rating: 4.9,
    reviewCount: 2450,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426da473b?w=800&auto=format&fit=crop"
    ],
    description: "Industry-leading noise cancellation. Up to 30-hour battery life with quick charging. Engineered to perfection.",
    badge: "Bestseller",
    stock: 15,
    tags: ["wireless", "noise-cancelling", "audio"]
  },
  {
    id: 2,
    title: "MacBook Pro 14-inch (M3 Pro)",
    category: "Electronics",
    price: 1999,
    originalPrice: 2199,
    rating: 4.8,
    reviewCount: 890,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop",
    description: "The most advanced chips for a pro laptop. Brutal battery life. A stunning Liquid Retina XDR display.",
    badge: "Premium",
    stock: 5,
    tags: ["laptop", "apple", "pro"]
  },
  {
    id: 3,
    title: "Samsung Odyssey Neo G9 Curved Monitor",
    category: "Electronics",
    price: 1299,
    originalPrice: 1599,
    rating: 4.7,
    reviewCount: 420,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop",
    description: "49-inch curved gaming monitor with Quantum Mini-LED. 240Hz refresh rate and 1ms response time.",
    badge: "Sale",
    stock: 8,
    tags: ["gaming", "monitor", "ultrawide"]
  },
  {
    id: 4,
    title: "Logitech MX Master 3S Wireless Mouse",
    category: "Electronics",
    price: 99,
    originalPrice: 110,
    rating: 4.9,
    reviewCount: 3100,
    image: "https://images.unsplash.com/photo-1629429464245-4874dd3badbc?w=800&auto=format&fit=crop",
    description: "Any-surface tracking - now 8K DPI. Quiet Clicks for a fluid, tactile feel. MagSpeed scrolling.",
    badge: "Top Rated",
    stock: 50,
    tags: ["mouse", "productivity", "wireless"]
  },
  {
    id: 5,
    title: "Keychron Q3 Pro Custom Keyboard",
    category: "Electronics",
    price: 189,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 150,
    image: "https://images.unsplash.com/photo-1620000617482-821324eb9a14?w=800&auto=format&fit=crop",
    description: "QMK/VIA wireless custom mechanical keyboard with aluminum body and double-gasket design.",
    badge: "Custom",
    stock: 12,
    tags: ["keyboard", "mechanical", "tech"]
  },

  // ── Clothing & Outerwear ──
  {
    id: 6,
    title: "Arc'teryx Beta AR Hardshell",
    category: "Outerwear",
    price: 750,
    originalPrice: 850,
    rating: 4.9,
    reviewCount: 560,
    image: "https://images.unsplash.com/photo-1544923246-77307dd654ca?w=800&auto=format&fit=crop",
    description: "Waterproof, windproof, and breathable. Built for all-round mountaineering and backcountry use.",
    badge: "Elite",
    stock: 10,
    tags: ["gore-tex", "outdoor", "jacket"]
  },
  {
    id: 7,
    title: "Patagonia Nano Puff Jacket",
    category: "Outerwear",
    price: 239,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 1200,
    image: "https://images.unsplash.com/photo-1467043153537-a4fba2cd39ef?w=800&auto=format&fit=crop",
    description: "Warm, windproof, water-resistant. Lightweight and highly compressible 100% recycled polyester insulation.",
    badge: "Eco-Friendly",
    stock: 25,
    tags: ["sustainable", "insulated", "lightweight"]
  },
  {
    id: 8,
    title: "Uniqlo Ultra Light Down Parka",
    category: "Clothing",
    price: 89,
    originalPrice: 120,
    rating: 4.5,
    reviewCount: 3400,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop",
    description: "Incredibly light and warm. Fills with premium down. Includes a convenient storage pouch.",
    badge: "Best Value",
    stock: 100,
    tags: ["classic", "casual", "warm"]
  },
  {
    id: 9,
    title: "Stone Island Garment Dyed Hoodie",
    category: "Clothing",
    price: 320,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 88,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&auto=format&fit=crop",
    description: "Made in Italy from soft brushed cotton. Garment dyed to achieve a unique, deep color intensity.",
    badge: "Streetwear",
    stock: 7,
    tags: ["luxury", "hoodie", "mens"]
  },
  {
    id: 10,
    title: "Levi's 501 Original Straight Jeans",
    category: "Clothing",
    price: 69,
    originalPrice: 89,
    rating: 4.6,
    reviewCount: 15600,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop",
    description: "The original straight fit jean. A cultural icon since 1873. Made with signature button fly.",
    badge: "Iconic",
    stock: 200,
    tags: ["denim", "essential", "vintage"]
  },

  // ── Footwear ──
  {
    id: 11,
    title: "Nike Air Jordan 1 Retro High OG",
    category: "Footwear",
    price: 180,
    originalPrice: 220,
    rating: 4.9,
    reviewCount: 5400,
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop",
    description: "The sneaker that started it all. Premium leather construction and legendary design.",
    badge: "Rare",
    stock: 4,
    tags: ["sneakers", "jordan", "streetwear"]
  },
  {
    id: 12,
    title: "New Balance 990v6 Made in USA",
    category: "Footwear",
    price: 200,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 320,
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&auto=format&fit=crop",
    description: "The ultimate dad shoe. Made in the USA with premium pigskin suede and mesh overlays.",
    badge: "Comfort",
    stock: 18,
    tags: ["heritage", "running", "lifestyle"]
  },
  {
    id: 13,
    title: "Salomon XT-6 Advanced",
    category: "Footwear",
    price: 190,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 450,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop",
    description: "The preferred shoe for world-class trail runners. Designed for long distances and harsh conditions.",
    badge: "Trending",
    stock: 22,
    tags: ["gorpcore", "trail", "active"]
  },
  {
    id: 14,
    title: "Allbirds Tree Runners",
    category: "Footwear",
    price: 105,
    originalPrice: 125,
    rating: 4.5,
    reviewCount: 2200,
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=800&auto=format&fit=crop",
    description: "Made from sustainably sourced eucalyptus tree fiber. Lightweight, breathable, and machine washable.",
    badge: "Sustainable",
    stock: 40,
    tags: ["carbon-neutral", "washable", "comfort"]
  },

  // ── Home & Kitchen ──
  {
    id: 15,
    title: "Fellow Stagg EKG Electric Kettle",
    category: "Home & Kitchen",
    price: 165,
    originalPrice: 195,
    rating: 4.9,
    reviewCount: 1100,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop",
    description: "Variable temperature control, gooseneck pour-over kettle. Minimalist design for coffee enthusiasts.",
    badge: "Design",
    stock: 15,
    tags: ["coffee", "kitchen", "premium"]
  },
  {
    id: 16,
    title: "Dyson V15 Detect Cordless Vacuum",
    category: "Home & Kitchen",
    price: 749,
    originalPrice: 849,
    rating: 4.8,
    reviewCount: 2000,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop",
    description: "Laser reveals microscopic dust. Intelligently optimizes suction and run time.",
    badge: "Smart Home",
    stock: 9,
    tags: ["dyson", "appliances", "cleaning"]
  },
  {
    id: 17,
    title: "Le Creuset Signature Dutch Oven",
    category: "Home & Kitchen",
    price: 380,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 4500,
    image: "https://images.unsplash.com/photo-1584281722573-0490425be259?w=800&auto=format&fit=crop",
    description: "An heirloom-quality dutch oven crafted with enameled cast iron. The center of any kitchen.",
    badge: "Classic",
    stock: 12,
    tags: ["cooking", "castiron", "luxury"]
  },
  {
    id: 18,
    title: "Philips Hue Smart Lighting Starter Kit",
    category: "Home & Kitchen",
    price: 159,
    originalPrice: 199,
    rating: 4.7,
    reviewCount: 8900,
    image: "https://images.unsplash.com/photo-1550524513-31705ec0bc92?w=800&auto=format&fit=crop",
    description: "Experience high-quality LED light that you can customize instantly. Transform your home atmosphere.",
    badge: "Tech Home",
    stock: 35,
    tags: ["lighting", "smart", "iot"]
  },

  // ── Accessories ──
  {
    id: 19,
    title: "Bellroy Transit Backpack",
    category: "Accessories",
    price: 239,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 120,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop",
    description: "A clever work-and-travel companion. Pockets for everything you need on the move.",
    badge: "Travel",
    stock: 10,
    tags: ["bag", "backpack", "essentials"]
  },
  {
    id: 20,
    title: "Ray-Ban Wayfarer Classic",
    category: "Accessories",
    price: 163,
    originalPrice: 185,
    rating: 4.7,
    reviewCount: 12000,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop",
    description: "The most recognizable style in the history of sunglasses. Modern since 1952.",
    badge: "Timeless",
    stock: 100,
    tags: ["sunglasses", "summer", "eyewear"]
  },
  {
    id: 21,
    title: "Peak Design Everyday Slide Camera Strap",
    category: "Accessories",
    price: 65,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 880,
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop",
    description: "The world's most versatile professional camera strap. Wear it as a sling, neck, or shoulder strap.",
    badge: "Pro Choice",
    stock: 25,
    tags: ["photography", "camera", "pro"]
  },

  // ── Fitness & Outdoor ──
  {
    id: 22,
    title: "Garmin Epix Pro (Gen 2)",
    category: "Fitness",
    price: 899,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 340,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop",
    description: "Ultimate high-performance multisport GPS smartwatch with a stunning AMOLED display.",
    badge: "New Arrival",
    stock: 10,
    tags: ["watch", "fitness", "gps"]
  },
  {
    id: 23,
    title: "Yeti Hopper Flip 12 Cooler",
    category: "Outdoor",
    price: 250,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 1560,
    image: "https://images.unsplash.com/photo-1594921132717-380d6f4618e9?w=800&auto=format&fit=crop",
    description: "The leakproof, tough-as-nails, carry-the-day soft cooler. Built for extreme conditions.",
    badge: "Rugged",
    stock: 15,
    tags: ["cooler", "camping", "yeti"]
  },
  {
    id: 24,
    title: "Theragun Pro Gen 5",
    category: "Fitness",
    price: 599,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 920,
    image: "https://images.unsplash.com/photo-1610484826967-09c5720778c7?w=800&auto=format&fit=crop",
    description: "Powerful percussive therapy. Smart features, quieter motor, and deep muscle relief.",
    badge: "Recovery",
    stock: 20,
    tags: ["massage", "wellness", "health"]
  },

  // ── More Electronics ──
  {
    id: 25,
    title: "Sony PlayStation 5 Console",
    category: "Electronics",
    price: 499,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 12000,
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&auto=format&fit=crop",
    description: "Experience lightning-fast loading with an ultra-high speed SSD and deeper immersion with haptic feedback.",
    badge: "Hot",
    stock: 2,
    tags: ["gaming", "console", "sony"]
  },
  {
    id: 26,
    title: "Fujifilm X100VI Digital Camera",
    category: "Electronics",
    price: 1599,
    originalPrice: null,
    rating: 5.0,
    reviewCount: 110,
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop",
    description: "The ultimate compact camera. Retro design, 40MP sensor, and in-body image stabilization.",
    badge: "Sold Out Soon",
    stock: 1,
    tags: ["camera", "photography", "retro"]
  },
  {
    id: 27,
    title: "Kindle Paperwhite signature Edition",
    category: "Electronics",
    price: 189,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 5600,
    image: "https://images.unsplash.com/photo-1592434134753-a70baf7979d7?w=800&auto=format&fit=crop",
    description: "Now with a 6.8\" display and thinner borders, adjustable warm light, and wireless charging.",
    badge: "Essentials",
    stock: 60,
    tags: ["books", "reader", "kindle"]
  },

  // ── More Clothing ──
  {
    id: 28,
    title: "Brooks Brothers Oxford Shirt",
    category: "Clothing",
    price: 98,
    originalPrice: 120,
    rating: 4.6,
    reviewCount: 340,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?w=800&auto=format&fit=crop",
    description: "The original button-down. Woven from Egyptian cotton. A staple of the American wardrobe.",
    badge: "Classic",
    stock: 45,
    tags: ["shirt", "formal", "mens"]
  },
  {
    id: 29,
    title: "Lululemon Align High-Rise Pant",
    category: "Fitness",
    price: 98,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 22000,
    image: "https://images.unsplash.com/photo-1506629082923-37604593cb84?w=800&auto=format&fit=crop",
    description: "When feeling nothing is everything. The Align collection, powered by Nulu™ fabric.",
    badge: "Best for Yoga",
    stock: 80,
    tags: ["yoga", "fitness", "women"]
  },
  {
    id: 30,
    title: "Ralph Lauren Pony Polo Shirt",
    category: "Clothing",
    price: 110,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 4500,
    image: "https://images.unsplash.com/photo-1582737637841-f705e4682006?w=800&auto=format&fit=crop",
    description: "An American style standard since 1972. Tailored through the waist for a modern silhouette.",
    badge: "Designer",
    stock: 55,
    tags: ["polo", "casual", "luxury"]
  }
];

export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Outerwear",
  "Footwear",
  "Home & Kitchen",
  "Accessories",
  "Fitness",
  "Outdoor"
];
