// Mock product data – simulates a real API response
export const products = [
  {
    id: 1,
    title: "Arc'teryx Beta AR Jacket",
    category: "Outerwear",
    price: 799,
    originalPrice: 950,
    rating: 4.8,
    reviewCount: 214,
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop",
    ],
    description: "The Beta AR is the most versatile hardshell in the Arc'teryx lineup. Built for all-round mountaineering use, it combines weather protection with freedom of movement.",
    badge: "Bestseller",
    stock: 12,
    tags: ["waterproof", "Gore-Tex", "hiking"],
  },
  {
    id: 2,
    title: "Sony WH-1000XM5 Headphones",
    category: "Electronics",
    price: 349,
    originalPrice: 399,
    rating: 4.9,
    reviewCount: 1482,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop",
    ],
    description: "Industry-leading noise cancellation with the new Integrated Processor V1. Up to 30-hour battery life and crystal-clear hands-free calling.",
    badge: "Top Rated",
    stock: 45,
    tags: ["wireless", "noise-cancelling", "premium"],
  },
  {
    id: 3,
    title: "Allbirds Tree Runners",
    category: "Footwear",
    price: 135,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=800&auto=format&fit=crop",
    ],
    description: "Made from sustainably sourced eucalyptus tree fiber. Incredibly light, breathable, and machine washable. Built for everyday wear.",
    badge: null,
    stock: 28,
    tags: ["sustainable", "comfort", "everyday"],
  },
  {
    id: 4,
    title: "Apple MacBook Pro 14\"",
    category: "Electronics",
    price: 1999,
    originalPrice: 2199,
    rating: 4.9,
    reviewCount: 3201,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&auto=format&fit=crop",
    ],
    description: "M3 Pro chip with 12-core CPU and 18-core GPU. Liquid Retina XDR display, up to 22 hours battery life. The ultimate pro laptop.",
    badge: "New",
    stock: 8,
    tags: ["laptop", "M3", "professional"],
  },
  {
    id: 5,
    title: "Levi's 501 Original Jeans",
    category: "Clothing",
    price: 69,
    originalPrice: 89,
    rating: 4.5,
    reviewCount: 5621,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop",
    ],
    description: "The original straight fit jean since 1873. Made from 100% cotton denim with the iconic button fly. Timeless style that only gets better with age.",
    badge: "Classic",
    stock: 60,
    tags: ["denim", "classic", "casual"],
  },
  {
    id: 6,
    title: "Fellow Stagg EKG Kettle",
    category: "Home & Kitchen",
    price: 165,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 342,
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop",
    ],
    description: "Variable temperature control electric kettle with 0.9L capacity. Precision pour spout for the perfect cup. Built-in stopwatch and hold mode.",
    badge: null,
    stock: 19,
    tags: ["coffee", "kettle", "kitchen"],
  },
  {
    id: 7,
    title: "Patagonia Nano Puff Jacket",
    category: "Outerwear",
    price: 279,
    originalPrice: 299,
    rating: 4.7,
    reviewCount: 988,
    image: "https://images.unsplash.com/photo-1467043153537-a4fba2cd39ef?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1467043153537-a4fba2cd39ef?w=800&auto=format&fit=crop",
    ],
    description: "Lightweight, wind-resistant, and highly compressible insulated jacket. Made from recycled materials with PrimaLoft® Gold Insulation Eco.",
    badge: "Eco",
    stock: 22,
    tags: ["insulated", "packable", "sustainable"],
  },
  {
    id: 8,
    title: "Dyson V15 Detect",
    category: "Home & Kitchen",
    price: 749,
    originalPrice: 849,
    rating: 4.8,
    reviewCount: 1103,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop",
    ],
    description: "Laser reveals microscopic dust. Automatically adapts suction. Scientifically proves what you've captured with an LCD screen that counts and sizes particles.",
    badge: "Sale",
    stock: 6,
    tags: ["vacuum", "cordless", "smart"],
  },
  {
    id: 9,
    title: "Uniqlo Ultra Light Down Jacket",
    category: "Clothing",
    price: 89,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 2341,
    image: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=800&auto=format&fit=crop",
    ],
    description: "Incredibly light down jacket that packs into its own pocket. 90% down fill for exceptional warmth-to-weight ratio. Perfect for layering.",
    badge: null,
    stock: 35,
    tags: ["down", "packable", "layering"],
  },
  {
    id: 10,
    title: "iPad Pro 11\"",
    category: "Electronics",
    price: 999,
    originalPrice: 1099,
    rating: 4.8,
    reviewCount: 2876,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop",
    ],
    description: "M4 chip. Ultra Retina XDR display with ProMotion. Apple Pencil Pro and Magic Keyboard compatible. The most powerful iPad ever.",
    badge: "New",
    stock: 15,
    tags: ["tablet", "M4", "creative"],
  },
  {
    id: 11,
    title: "Salomon Speedcross 6",
    category: "Footwear",
    price: 145,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 734,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&auto=format&fit=crop",
    ],
    description: "Aggressive trail running shoe with iconic cross-shaped lugs for grip in the muddiest conditions. Quicklace system for on-the-fly adjustments.",
    badge: null,
    stock: 42,
    tags: ["trail", "running", "grip"],
  },
  {
    id: 12,
    title: "Ember Temperature Control Mug",
    category: "Home & Kitchen",
    price: 99,
    originalPrice: 119,
    rating: 4.5,
    reviewCount: 589,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop",
    ],
    description: "Smart mug that keeps your coffee at the perfect temperature all morning. Control via app. 1.5 hour battery life on a single charge.",
    badge: "Smart",
    stock: 30,
    tags: ["coffee", "smart", "ceramic"],
  },
];

export const categories = [
  "All",
  "Electronics",
  "Clothing",
  "Outerwear",
  "Footwear",
  "Home & Kitchen",
];
