name: CI/CD React App (Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Copy project to EC2
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/app"

    # Run deployment commands on EC2
    - name: Deploy using Docker Compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app

          # Stop old containers
          docker-compose down

          # Build new images
          docker-compose build --no-cache

          # Start containers
          docker-compose up -d

          # Clean unused images
          docker system prune -f